export const ui = {
  skipToContent: "تخط إلى المحتوى الرئيسي",
  mobileMenuDescription: "قائمة التنقل الرئيسية",
  search: {
    ariaLabel: "بحث",
    title: "بحث عام",
    description: "ابحث عن منتجات ومقالات وصفحات",
    placeholder: "ابحث عن منتجات أو مقالات أو صفحات...",
    empty: "لا توجد نتائج",
    headings: {
      slots: "المواعيد القادمة",
      products: "منتجات",
      pages: "صفحات",
      posts: "أخبار",
    },
  },
  spinner: {
    ariaLabel: "جاري التحميل",
  },
  navbar: {
    desktopAriaLabel: "التنقل الرئيسي",
    whatsappAriaLabel: "إرسال رسالة عبر واتساب",
    whatsappTitle: "اتصل بنا",
    menuAriaLabel: "فتح القائمة",
    mobileNavAriaLabel: "القائمة المحمولة",
    closeAria: "إغلاق",
    openAria: "فتح",
    themeAriaLabel: "تبديل الوضع الداكن/الفاتح",
    langAriaLabel: "تغيير اللغة",
    langEs: "ES",
    langEn: "EN",
  },
  footer: {
    noSlots: "لا توجد مواعيد متاحة",
  },
  dropdown: {
    noSlots: "لا توجد مواعيد متاحة",
  },
  social: {
    correo: "بريد",
    instagram: "انستغرام",
    facebook: "فيسبوك",
    twitter: "تويتر",
    youtube: "يوتيوب",
  },
  share: {
    label: "مشاركة",
    description: "انسخ الرابط أو شارك على وسائل التواصل",
    copyLabel: "انسخ الرابط للمشاركة:",
    copyAriaLabel: "نسخ الرابط إلى الحافظة",
    socialLabel: "مشاركة على وسائل التواصل:",
    twitter: "مشاركة على X",
    facebook: "مشاركة على فيسبوك",
    linkedin: "مشاركة على لينكد إن",
    email: "مشاركة عبر البريد",
    twitterShort: "X",
    facebookShort: "FB",
    linkedinShort: "IN",
    emailShort: "ML",
    emailSubject: (title: string) => `مشاركة: ${title}`,
    emailSubjectFallback: "مشاركة رابط",
    toastSuccess: "تم نسخ الرابط إلى الحافظة",
    toastError: "خطأ في نسخ الرابط",
  },
  whatsapp: {
    dialog: {
      title: "إرسال عبر واتساب",
      description:
        "أدخل رقم واتساب الخاص بك لاستلام المعلومات.",
      searchCountry: "ابحث عن بلد...",
      countryNotFound: "لم يتم العثور على البلد",
      phonePlaceholder: "رقم الهاتف",
      previewLabel: "الرسالة المراد إرسالها:",
      hint: "سيتم فتح واتساب مع الرسالة المعدة مسبقاً. فقط اضغط إرسال.",
      cancel: "إلغاء",
      send: "إرسال",
      sending: "جاري الإرسال...",
    },
    sent: {
      title: "تم إرسال الرسالة",
      description: "لقد تلقينا استفسارك",
      message: "سنرد عليك قريباً. شكراً لتواصلك معنا.",
      retry: "إعادة المحاولة",
      close: "إغلاق",
    },
    notification: {
      success: "تم إرسال الرسالة بنجاح",
      rateLimit: "انتظر 30 ثانية لإعادة الإرسال",
      error: "خطأ في إرسال الرسالة",
    },
    send: {
      ycloudDisabled: "YCloud معطل",
      notConfigured: "API واتساب غير مهيأ",
      numberNotConfigured: "رقم العمل غير مهيأ",
      missingParams: "معلمات مطلوبة مفقودة",
      rateLimitIp: "تمهل. حاول بعد 30 ثانية.",
      rateLimitTo:
        "رسائل كثيرة لهذا الرقم. انتظر 30 ثانية.",
      rateLimitGlobal: "رسائل كثيرة مرسلة. حاول لاحقاً.",
      rateLimitMinute: "طلبات كثيرة. انتظر دقيقة.",
      rateLimitHour: "لقد وصلت إلى حد الرسائل في الساعة.",
      rateLimitRecipient:
        "هذا الرقم تلقى عدة رسائل. حاول لاحقاً.",
      sendError: "خطأ في إرسال الرسالة",
    },
  },
  copyright: (year: number, brandName: string) =>
    `© ${year} ${brandName}. جميع الحقوق محفوظة.`,
  cookie: {
    title: "سياسة ملفات تعريف الارتباط",
    description:
      "نستخدم ملفات تعريف الارتباط لتحسين تجربتك. يمكنك قبول جميع ملفات تعريف الارتباط أو تخصيص تفضيلاتك.",
    necessary: "ضرورية",
    alwaysActive: "نشطة دائماً",
    analytics: "تحليلية",
    analyticsHelper: "تساعدنا على التحسين",
    marketing: "تسويقية",
    marketingHelper: "تخصيص الإعلانات",
    reject: "رفض",
    save: "حفظ",
    acceptAll: "قبول الكل",
    accepted: "تم قبول ملفات تعريف الارتباط",
    onlyNecessary: "ملفات تعريف الارتباط الضرورية فقط",
    saved: "تم حفظ التفضيلات",
  },
  agent: {
    sendError: "عذراً، حدثت مشكلة. حاول مرة أخرى.",
    derivedToHuman: "[تم تحويل المحادثة إلى بشري]",
    queued: "[في الانتظار، بانتظار المزيد من الرسائل...]",
  },
  notFound: {
    product: "المنتج غير موجود",
    article: "المقال غير موجود",
    page: "الصفحة غير موجودة",
  },
  pagination: {
    ariaLabel: "ترقيم الصفحات",
    previous: "السابق",
    previousAria: "الذهاب إلى الصفحة السابقة",
    next: "التالي",
    nextAria: "الذهاب إلى الصفحة التالية",
    more: "المزيد من الصفحات",
  },
  breadcrumb: {
    ariaLabel: "مسار التنقل",
    more: "المزيد",
  },
  sidebar: {
    toggleAria: "تبديل الشريط الجانبي",
    toggleTitle: "تبديل الشريط الجانبي",
    sheetTitle: "الشريط الجانبي",
    sheetDescription: "عرض الشريط الجانبي المحمول.",
    toggleSrOnly: "تبديل الشريط الجانبي",
  },
  og: {
    logoAlt: "شعار",
    backgroundAlt: "خلفية",
    productFallback: "منتج",
  },
  media: {
    image: (desc: string) => `[صورة: ${desc}]`,
    imageSimple: "[صورة]",
    audio: (text: string) => `[صوت مفرغ: ${text}]`,
    audioSimple: "[صوت]",
    voice: (text: string) => `[ملاحظة صوتية مفرغة: ${text}]`,
    voiceSimple: "[ملاحظة صوتية]",
    video: (caption: string) => `[فيديو: ${caption || ""}]`,
    videoSimple: "[فيديو]",
    pdf: (text: string) => `[PDF مستخرج: ${text}]`,
    doc: (name: string) => `[مستند: ${name || "بدون اسم"}]`,
    sticker: "[ملصق]",
    location: (name: string, address: string, lat?: number, lng?: number) =>
      `[موقع: ${[name, address].filter(Boolean).join(", ")}]${lat && lng ? ` (GPS: ${lat}, ${lng})` : ""}`,
    contact: (info: string) => `[جهة اتصال: ${info}]`,
    order: (productId: string, qty: number) =>
      `[طلب: منتج ${productId || "غير معروف"}, الكمية ${qty || 1}]`,
    system: (body: string) => `[نظام: ${body || "حدث النظام"}]`,
    unsupported: (type: string) => `[رسالة من نوع "${type}" غير مدعومة]`,
    welcomeText: "مرحباً، أنا عميل جديد",
  },
  api: {
    slugInvalid: "معرف غير صالح",
    entityNotFound: (entity: string) => `${entity} غير موجود`,
    serverErrorEntity: (entity: string) => `خطأ في الحصول على ${entity}`,
    serverError: "خطأ داخلي في الخادم",
    unauthorized: "غير مصرح. قدم ترويسة x-api-key.",
    missingParam: (param: string) => `${param} مطلوب`,
    unknown: "خطأ غير معروف",
  },
};
