export const ui = {

  skipToContent: "Saltar al contenido principal",
  mobileMenuDescription: "Menú de navegación principal",
  search: {
    ariaLabel: "Search",
    title: "Búsqueda global",
    description: "Busca productos, artículos y páginas",
    placeholder: "Buscar productos, artículos o páginas...",
    empty: "Sin resultados",
    headings: {
      slots: "Próximas citas",
      products: "Productos",
      pages: "Páginas",
      posts: "Blog",
    },
  },
  spinner: {
    ariaLabel: "Cargando",
  },
  navbar: {
    desktopAriaLabel: "Navegación principal",
    whatsappAriaLabel: "Enviar mensaje por WhatsApp",
    whatsappTitle: "Contacto",
    menuAriaLabel: "Abrir menú",
    mobileNavAriaLabel: "Menú móvil",
    closeAria: "Cerrar",
    openAria: "Abrir",
    themeAriaLabel: "Cambiar tema oscuro/claro",
    langAriaLabel: "Cambiar idioma",
    langEs: "ES",
    langEn: "EN",
  },
  footer: {
    noSlots: "No citas disponibles",
  },
  dropdown: {
    noSlots: "No citas disponibles",
  },
  social: {
    correo: "Correo",
    instagram: "Instagram",
    facebook: "Facebook",
    twitter: "Twitter",
    youtube: "YouTube",
  },
  share: {
    label: "Compartir",
    description: "Copia el enlace o comparte en redes sociales",
    copyLabel: "Copia el enlace para compartir:",
    copyAriaLabel: "Copiar enlace al portapapeles",
    socialLabel: "Compartir en redes:",
    twitter: "Compartir en X",
    facebook: "Compartir en Facebook",
    linkedin: "Compartir en LinkedIn",
    email: "Compartir por correo",
    twitterShort: "X",
    facebookShort: "FB",
    linkedinShort: "IN",
    emailShort: "ML",
    emailSubject: (title: string) => `Compartir: ${title}`,
    emailSubjectFallback: "Compartir enlace",
    toastSuccess: "Enlace copiado al portapapeles",
    toastError: "Error al copiar enlace",
  },
  whatsapp: {
    dialog: {
      title: "Enviar por WhatsApp",
      description: "Ingresa tu n\u00famero de WhatsApp para recibir la informaci\u00f3n.",
      searchCountry: "Buscar pa\u00eds...",
      countryNotFound: "Pa\u00eds no encontrado",
      phonePlaceholder: "N\u00famero de tel\u00e9fono",
      previewLabel: "Mensaje a enviar:",
      hint: "WhatsApp se abrir\u00e1 con el mensaje pre-escrito. Solo presiona enviar.",
      cancel: "Cancelar",
      send: "Enviar",
      sending: "Enviando...",
    },
    sent: {
      title: "Mensaje enviado",
      description: "Hemos recibido tu consulta",
      message: "Te responderemos a la brevedad. Gracias por contactarnos.",
      retry: "Reintentar",
      close: "Cerrar",
    },
    notification: {
      success: "Mensaje enviado correctamente",
      rateLimit: "Espera 30s para reenviar",
      error: "Error al enviar mensaje",
    },
    send: {
      ycloudDisabled: "YCloud deshabilitado",
      notConfigured: "WhatsApp API no configurada",
      numberNotConfigured: "N\u00famero de negocio no configurado",
      missingParams: "Faltan par\u00e1metros requeridos",
      rateLimitIp: "M\u00e1s despacio. Int\u00e9ntalo en 30 segundos.",
      rateLimitTo: "Demasiados mensajes a este n\u00famero. Espera 30 segundos.",
      rateLimitGlobal: "Demasiados mensajes enviados. Intenta m\u00e1s tarde.",
      rateLimitMinute: "Demasiadas solicitudes. Espera un minuto.",
      rateLimitHour: "Has alcanzado el l\u00edmite de mensajes por hora.",
      rateLimitRecipient: "Este n\u00famero ya ha recibido varios mensajes. Intenta m\u00e1s tarde.",
      sendError: "Error al enviar mensaje",
    },
  },
  copyright: (year: number, brandName: string) =>
    `© ${year} ${brandName}. Todos los derechos reservados.`,
  cookie: {
    title: "Política de Cookies",
    description:
      "Utilizamos cookies para mejorar tu experiencia. Puedes aceptar todas las cookies o personalizar tus preferencias.",
    necessary: "Necesarias",
    alwaysActive: "Siempre activas",
    analytics: "Analíticas",
    analyticsHelper: "Nos ayudan a mejorar",
    marketing: "Marketing",
    marketingHelper: "Personalización de anuncios",
    reject: "Rechazar",
    save: "Guardar",
    acceptAll: "Aceptar todo",
    accepted: "Cookies aceptadas",
    onlyNecessary: "Solo cookies necesarias",
    saved: "Preferencias guardadas",
  },
  agent: {
    sendError: "Lo siento, tuve un problema. Intenta de nuevo.",
    derivedToHuman: "[chat derivado a humano]",
    queued: "[en cola, esperando más mensajes...]",
  },
  notFound: {
    product: "Producto no encontrado",
    article: "Artículo no encontrado",
    page: "Página no encontrada",
  },
  pagination: {
    ariaLabel: "Paginación",
    previous: "Anterior",
    previousAria: "Ir a la página anterior",
    next: "Siguiente",
    nextAria: "Ir a la página siguiente",
    more: "Más páginas",
  },
  breadcrumb: {
    ariaLabel: "Miga de pan",
    more: "Más",
  },
  sidebar: {
    toggleAria: "Alternar barra lateral",
    toggleTitle: "Alternar barra lateral",
    sheetTitle: "Barra lateral",
    sheetDescription: "Muestra la barra lateral móvil.",
    toggleSrOnly: "Alternar barra lateral",
  },
  og: {
    logoAlt: "Logotipo",
    backgroundAlt: "Fondo",
    productFallback: "Producto",
  },
  media: {
    image: (desc: string) => `[Imagen: ${desc}]`,
    imageSimple: "[Imagen]",
    audio: (text: string) => `[Audio transcrito: ${text}]`,
    audioSimple: "[Audio]",
    voice: (text: string) => `[Nota de voz transcrita: ${text}]`,
    voiceSimple: "[Nota de voz]",
    video: (caption: string) => `[Video: ${caption || ""}]`,
    videoSimple: "[Video]",
    pdf: (text: string) => `[PDF extraído: ${text}]`,
    doc: (name: string) => `[Documento: ${name || "sin nombre"}]`,
    sticker: "[Sticker]",
    location: (name: string, address: string, lat?: number, lng?: number) =>
      `[Ubicación: ${[name, address].filter(Boolean).join(", ")}]${lat && lng ? ` (GPS: ${lat}, ${lng})` : ""}`,
    contact: (info: string) => `[Contacto: ${info}]`,
    order: (productId: string, qty: number) => `[Pedido: producto ${productId || "desconocido"}, cantidad ${qty || 1}]`,
    system: (body: string) => `[Sistema: ${body || "evento del sistema"}]`,
    unsupported: (type: string) => `[Mensaje tipo "${type}" no soportado]`,
    welcomeText: "Hola, soy nuevo cliente",
  },
  api: {
    slugInvalid: "Slug inválido",
    entityNotFound: (entity: string) => `${entity} no encontrado`,
    serverErrorEntity: (entity: string) => `Error al obtener ${entity}`,
    serverError: "Error interno del servidor",
    unauthorized: "No autorizado. Provee header x-api-key.",
    missingParam: (param: string) => `${param} requerido`,
    unknown: "Error desconocido",
  },
};
