export const ui = {

  skipToContent: "Skip to main content",
  mobileMenuDescription: "Main navigation menu",
  search: {
    ariaLabel: "Search",
    title: "Global search",
    description: "Search products, articles and pages",
    placeholder: "Search products, articles or pages...",
    empty: "No results",
    headings: {
      slots: "Upcoming appointments",
      products: "Products",
      pages: "Pages",
      posts: "Blog",
    },
  },
  spinner: {
    ariaLabel: "Loading",
  },
  navbar: {
    desktopAriaLabel: "Main navigation",
    whatsappAriaLabel: "Send WhatsApp message",
    whatsappTitle: "Contact",
    menuAriaLabel: "Open menu",
    mobileNavAriaLabel: "Mobile menu",
    closeAria: "Close",
    openAria: "Open",
    themeAriaLabel: "Toggle dark mode",
    langAriaLabel: "Switch language",
    langEs: "ES",
    langEn: "EN",
  },
  footer: {
    noSlots: "No appointments available",
  },
  dropdown: {
    noSlots: "No appointments available",
  },
  social: {
    correo: "Email",
    instagram: "Instagram",
    facebook: "Facebook",
    twitter: "Twitter",
    youtube: "YouTube",
  },
  share: {
    label: "Share",
    description: "Copy the link or share on social media",
    copyLabel: "Copy link to share:",
    copyAriaLabel: "Copy link to clipboard",
    socialLabel: "Share on:",
    twitter: "Share on X",
    facebook: "Share on Facebook",
    linkedin: "Share on LinkedIn",
    email: "Share via email",
    twitterShort: "X",
    facebookShort: "FB",
    linkedinShort: "IN",
    emailShort: "ML",
    emailSubject: (title: string) => `Share: ${title}`,
    emailSubjectFallback: "Share link",
    toastSuccess: "Link copied to clipboard",
    toastError: "Failed to copy link",
  },
  whatsapp: {
    dialog: {
      title: "Send via WhatsApp",
      description: "Enter your WhatsApp number to receive the information.",
      searchCountry: "Search country...",
      countryNotFound: "Country not found",
      phonePlaceholder: "Phone number",
      previewLabel: "Message to send:",
      hint: "WhatsApp will open with the pre-written message. Just press send.",
      cancel: "Cancel",
      send: "Send",
      sending: "Sending...",
    },
    sent: {
      title: "Message sent",
      description: "We have received your inquiry",
      message: "We will get back to you shortly. Thank you for contacting us.",
      retry: "Retry",
      close: "Close",
    },
    notification: {
      success: "Message sent successfully",
      rateLimit: "Wait 30s to resend",
      error: "Error sending message",
    },
    send: {
      ycloudDisabled: "YCloud disabled",
      notConfigured: "WhatsApp API not configured",
      numberNotConfigured: "Business number not configured",
      missingParams: "Missing required parameters",
      rateLimitIp: "Slow down. Try again in 30 seconds.",
      rateLimitTo: "Too many messages to this number. Wait 30 seconds.",
      rateLimitGlobal: "Too many messages sent. Try again later.",
      rateLimitMinute: "Too many requests. Wait a minute.",
      rateLimitHour: "You have reached the hourly message limit.",
      rateLimitRecipient: "This number has received several messages. Try again later.",
      sendError: "Error sending message",
    },
  },
  copyright: (year: number, brandName: string) =>
    `© ${year} ${brandName}. All rights reserved.`,
  cookie: {
    title: "Cookie Policy",
    description:
      "We use cookies to improve your experience. You can accept all cookies or customize your preferences.",
    necessary: "Necessary",
    alwaysActive: "Always active",
    analytics: "Analytics",
    analyticsHelper: "Help us improve",
    marketing: "Marketing",
    marketingHelper: "Ad personalization",
    reject: "Reject",
    save: "Save",
    acceptAll: "Accept All",
    accepted: "Cookies accepted",
    onlyNecessary: "Only necessary cookies",
    saved: "Preferences saved",
  },
  agent: {
    sendError: "Sorry, I had a problem. Please try again.",
    derivedToHuman: "[chat derived to human]",
    queued: "[queued, waiting for more messages...]",
  },
  notFound: {
    product: "Product not found",
    article: "Article not found",
    page: "Page not found",
  },
  pagination: {
    ariaLabel: "Pagination",
    previous: "Previous",
    previousAria: "Go to previous page",
    next: "Next",
    nextAria: "Go to next page",
    more: "More pages",
  },
  breadcrumb: {
    ariaLabel: "Breadcrumb",
    more: "More",
  },
  sidebar: {
    toggleAria: "Toggle Sidebar",
    toggleTitle: "Toggle Sidebar",
  },
  og: {
    logoAlt: "Logo",
    backgroundAlt: "Background",
    productFallback: "Product",
  },
  media: {
    image: (desc: string) => `[Image: ${desc}]`,
    imageSimple: "[Image]",
    audio: (text: string) => `[Audio transcribed: ${text}]`,
    audioSimple: "[Audio]",
    voice: (text: string) => `[Voice note transcribed: ${text}]`,
    voiceSimple: "[Voice note]",
    video: (caption: string) => `[Video: ${caption || ""}]`,
    videoSimple: "[Video]",
    pdf: (text: string) => `[PDF extracted: ${text}]`,
    doc: (name: string) => `[Document: ${name || "unnamed"}]`,
    sticker: "[Sticker]",
    location: (name: string, address: string, lat?: number, lng?: number) =>
      `[Location: ${[name, address].filter(Boolean).join(", ")}]${lat && lng ? ` (GPS: ${lat}, ${lng})` : ""}`,
    contact: (info: string) => `[Contact: ${info}]`,
    order: (productId: string, qty: number) => `[Order: product ${productId || "unknown"}, quantity ${qty || 1}]`,
    system: (body: string) => `[System: ${body || "system event"}]`,
    unsupported: (type: string) => `[Message type "${type}" not supported]`,
    welcomeText: "Hello, I\u2019m a new customer",
  },
  api: {
    slugInvalid: "Invalid slug",
    entityNotFound: (entity: string) => `${entity} not found`,
    serverErrorEntity: (entity: string) => `Error fetching ${entity}`,
    serverError: "Internal server error",
    unauthorized: "Unauthorized. Provide x-api-key header.",
    missingParam: (param: string) => `${param} required`,
    unknown: "Unknown error",
  },
};
