export const ui = {

  mobileMenuDescription: "Main navigation menu",
  search: {
    ariaLabel: "Search",
    title: "Global search",
    description: "Search products, articles and pages",
    placeholder: "Search products, articles or pages...",
    empty: "No results",
    headings: {
      slots: "Upcoming appointments",
      products: "Products",
      pages: "Pages",
      posts: "Blog",
    },
  },
  spinner: {
    ariaLabel: "Loading",
  },
  navbar: {
    desktopAriaLabel: "Main navigation",
    whatsappAriaLabel: "Send WhatsApp message",
    whatsappTitle: "Contact",
    menuAriaLabel: "Open menu",
    mobileNavAriaLabel: "Mobile menu",
    closeAria: "Close",
    openAria: "Open",
  },
  footer: {
    noSlots: "No appointments available",
  },
  dropdown: {
    noSlots: "No appointments available",
  },
  social: {
    correo: "Email",
    instagram: "Instagram",
    facebook: "Facebook",
    twitter: "Twitter",
    youtube: "YouTube",
  },
  share: {
    label: "Share",
    description: "Copy the link or share on social media",
    copyLabel: "Copy link to share:",
    copyAriaLabel: "Copy link to clipboard",
    socialLabel: "Share on:",
    twitter: "Share on X",
    facebook: "Share on Facebook",
    linkedin: "Share on LinkedIn",
    email: "Share via email",
    emailSubject: (title: string) => `Share: ${title}`,
    emailSubjectFallback: "Share link",
    toastSuccess: "Link copied to clipboard",
    toastError: "Failed to copy link",
  },
  whatsapp: {
    dialog: {
      title: "Send via WhatsApp",
      description: "Enter your WhatsApp number to receive the information.",
      searchCountry: "Search country...",
      countryNotFound: "Country not found",
      phonePlaceholder: "WhatsApp number",
      previewLabel: "Message to send:",
      hint: "If it starts with 0 (e.g., 096 1234 123), enter it without the 0 (96 1234 123)",
      cancel: "Cancel",
      send: "Send via WhatsApp",
      sending: "Sending...",
    },
    sent: {
      title: "Message sent",
      description: "The message has been sent to your WhatsApp.",
      message: "Check your WhatsApp to continue the conversation.",
      retry: "Send to another number",
      close: "Close",
    },
    notification: {
      success: "Message sent successfully",
      rateLimit: "Wait 30s to resend",
      error: "Error sending message",
    },
  },
  copyright: (year: number, brandName: string) =>
    `© ${year} ${brandName}. All rights reserved.`,
  cookie: {
    title: "Cookie Policy",
    description:
      "We use cookies to improve your experience. You can accept all cookies or customize your preferences.",
    necessary: "Necessary",
    alwaysActive: "Always active",
    analytics: "Analytics",
    analyticsHelper: "Help us improve",
    marketing: "Marketing",
    marketingHelper: "Ad personalization",
    reject: "Reject",
    save: "Save",
    acceptAll: "Accept All",
    accepted: "Cookies accepted",
    onlyNecessary: "Only necessary cookies",
    saved: "Preferences saved",
  },
};
