export const ui = {
  loading: "Cargando...",
  notFound: "Página no encontrada",
  openingWhatsApp: "Abriendo WhatsApp...",
  mobileMenuDescription: "Menú de navegación principal",
  skipToContent: "Saltar al contenido principal",
  search: {
    ariaLabel: "Search",
    title: "Búsqueda global",
    description: "Busca productos, artículos y páginas",
    placeholder: "Buscar productos, artículos o páginas...",
    empty: "Sin resultados",
    headings: {
      slots: "Próximas citas",
      products: "Productos",
      pages: "Páginas",
      posts: "Blog",
    },
  },
  spinner: {
    ariaLabel: "Cargando",
  },
  navbar: {
    desktopAriaLabel: "Navegación principal",
    whatsappAriaLabel: "Enviar mensaje por WhatsApp",
    menuAriaLabel: "Abrir menú",
    mobileNavAriaLabel: "Menú móvil",
  },
  footer: {
    noSlots: "No citas disponibles",
  },
  dropdown: {
    noSlots: "No citas disponibles",
  },
  social: {
    correo: "Correo",
    instagram: "Instagram",
    facebook: "Facebook",
    twitter: "Twitter",
    youtube: "YouTube",
  },
  share: {
    label: "Compartir",
    description: "Copia el enlace o comparte en redes sociales",
    copyLabel: "Copia el enlace para compartir:",
    copyAriaLabel: "Copiar enlace al portapapeles",
    socialLabel: "Compartir en redes:",
    twitter: "Compartir en X",
    facebook: "Compartir en Facebook",
    linkedin: "Compartir en LinkedIn",
    email: "Compartir por correo",
    emailSubject: (title: string) => `Compartir: ${title}`,
    emailSubjectFallback: "Compartir enlace",
    toastSuccess: "Enlace copiado al portapapeles",
    toastError: "Error al copiar el enlace",
  },
  copyright: (year: number, brandName: string) =>
    `© ${year} ${brandName}. Todos los derechos reservados.`,
  cookie: {
    title: "Política de Cookies",
    description:
      "Utilizamos cookies para mejorar tu experiencia. Puedes aceptar todas las cookies o personalizar tus preferencias.",
    necessary: "Necesarias",
    alwaysActive: "Siempre activas",
    analytics: "Analíticas",
    analyticsHelper: "Nos ayudan a mejorar",
    marketing: "Marketing",
    marketingHelper: "Personalización de anuncios",
    reject: "Rechazar",
    save: "Guardar",
    acceptAll: "Aceptar todo",
  },
};
