export const ui = {
  loading: "Cargando...",
  notFound: "Página no encontrada",
  mobileMenuDescription: "Menú de navegación principal",
  skipToContent: "Saltar al contenido principal",
  search: {
    ariaLabel: "Search",
    title: "Búsqueda global",
    description: "Busca productos, artículos y páginas",
    placeholder: "Buscar productos, artículos o páginas...",
    empty: "Sin resultados",
    headings: {
      slots: "Próximas citas",
      products: "Productos",
      pages: "Páginas",
      posts: "Blog",
    },
  },
  spinner: {
    ariaLabel: "Cargando",
  },
  navbar: {
    desktopAriaLabel: "Navegación principal",
    whatsappAriaLabel: "Enviar mensaje por WhatsApp",
    whatsappTitle: "Contacto",
    menuAriaLabel: "Abrir menú",
    mobileNavAriaLabel: "Menú móvil",
  },
  footer: {
    noSlots: "No citas disponibles",
  },
  dropdown: {
    noSlots: "No citas disponibles",
  },
  social: {
    correo: "Correo",
    instagram: "Instagram",
    facebook: "Facebook",
    twitter: "Twitter",
    youtube: "YouTube",
  },
  share: {
    label: "Compartir",
    description: "Copia el enlace o comparte en redes sociales",
    copyLabel: "Copia el enlace para compartir:",
    copyAriaLabel: "Copiar enlace al portapapeles",
    socialLabel: "Compartir en redes:",
    twitter: "Compartir en X",
    facebook: "Compartir en Facebook",
    linkedin: "Compartir en LinkedIn",
    email: "Compartir por correo",
    emailSubject: (title: string) => `Compartir: ${title}`,
    emailSubjectFallback: "Compartir enlace",
    toastSuccess: "Enlace copiado al portapapeles",
    toastError: "Error al copiar el enlace",
  },
  whatsapp: {
    dialog: {
      title: "Enviar por WhatsApp",
      description: "Ingresa tu n\u00famero de WhatsApp para recibir la informaci\u00f3n.",
      searchCountry: "Buscar pa\u00eds...",
      countryNotFound: "Pa\u00eds no encontrado",
      phonePlaceholder: "N\u00famero de WhatsApp",
      previewLabel: "Mensaje a enviar:",
      hint: "Si empieza con 0 (ej: 096 1234 123), ingr\u00e9salo sin el 0 (96 1234 123)",
      cancel: "Cancelar",
      send: "Enviar por WhatsApp",
      sending: "Enviando...",
    },
    sent: {
      title: "Mensaje enviado",
      description: "El mensaje se ha enviado correctamente a tu WhatsApp.",
      message: "Revisa tu WhatsApp para continuar la conversaci\u00f3n.",
      retry: "Enviar a otro n\u00famero",
      close: "Cerrar",
    },
    notification: {
      success: "Mensaje enviado. Revisa tu WhatsApp.",
      rateLimit: "Espera 30 segundos antes de enviar otro mensaje.",
      error: "Error al enviar el mensaje. Intenta de nuevo.",
    },
  },
  copyright: (year: number, brandName: string) =>
    `© ${year} ${brandName}. Todos los derechos reservados.`,
  cookie: {
    title: "Política de Cookies",
    description:
      "Utilizamos cookies para mejorar tu experiencia. Puedes aceptar todas las cookies o personalizar tus preferencias.",
    necessary: "Necesarias",
    alwaysActive: "Siempre activas",
    analytics: "Analíticas",
    analyticsHelper: "Nos ayudan a mejorar",
    marketing: "Marketing",
    marketingHelper: "Personalización de anuncios",
    reject: "Rechazar",
    save: "Guardar",
    acceptAll: "Aceptar todo",
  },
};
