export const ui = {
  loading: "Cargando...",
  notFound: "P\u00e1gina no encontrada",
  openingWhatsApp: "Abriendo WhatsApp...",
  demo: {
    title: "Style Overview",
    description:
      "Designers love packing quirky glyphs into test phrases. This is a preview of the typography styles.",
    button: "Button",
    secondary: "Secondary",
    outline: "Outline",
    ghost: "Ghost",
    twoFactorAuth: "Two-factor authentication",
    verifyVia: "Verify via email or phone number.",
    enable: "Enable",
    namePlaceholder: "Name",
    messagePlaceholder: "Message",
    badge: "Badge",
    alertDialog: "Alert Dialog",
    dialog: "Dialog",
    allowAccessory: "Allow accessory to connect?",
    allowAccessoryDesc:
      "Do you want to allow the USB accessory to connect to this device and your data?",
    dontAllow: "Don\u2019t allow",
    allow: "Allow",
    buttonGroup: "Button Group",
    quickActions: "Quick Actions",
    mute: "Mute Conversation",
    markRead: "Mark as Read",
    blockUser: "Block User",
    conversation: "Conversation",
    share: "Share Conversation",
    copy: "Copy Conversation",
    report: "Report Conversation",
    delete: "Delete Conversation",
    sliderLabel: "Volume",
  },
}
